### ISSUE TITLE
kruise helmchart  1.5.2 missing the changes for MutatingWebhookConfiguration

### ISSUE THREAD

**Issue by abbshr** [openkruise/charts#94]
this is the original 1.5.2 pr which introduced the kube-system namespace excluded for `mpod.kb.io` namespaceSelector in `kruise\templates\webhookconfiguration.yaml`:
- pr: https://github.com/openkruise/charts/commit/52e41dc9c7814043f5b21f40e2e6ff3db6d177d9
- commit line: https://github.com/openkruise/charts/blob/089189d58ac4e4b554767d005ba3c0cb44f5d062/versions/kruise/1.5.2/templates/webhookconfiguration.yaml#L16-L25
![image](https://github.com/openkruise/charts/assets/3054411/a62a2816-c4e3-44df-88e7-78f030e828d3)

but in the halm chart 1.5.2, the latest changes for the namespaceSelector were missing:
- helm chart 1.5.2：https://github.com/openkruise/charts/releases/download/kruise-1.5.2/kruise-1.5.2.tgz
![image](https://github.com/openkruise/charts/assets/3054411/52529e19-13f1-4d0a-83ad-3dfb0165829a)

**Comment by furykerry** [comment]
the exclusion of kube-system is avaialble in 1.6.0 helm chart:
https://github.com/openkruise/charts/pull/95/files#diff-0c128c764f13a0883f1f188d84b75bdd0e4112d272d4e40efd84a54f5af56a43
